[티버, 포도당] 영상 CRUD
woowahan-ioi/miniprojects-2019 pull request #25
Opened 2019-08-14 08:54 UTC by backlo

2019-08-15 12:26 UTC, MrKwon requested changes
안녕하세요 ! 리뷰어 루피입니다.🤠
몇 가지 코멘트 남겼으니 확인해주세요.
프로덕션 코드들을 보고 나니 테스트 코드들도 매우 기대가 되네요 !

2019-08-15 12:26 UTC, MrKwon commented on src/main/java/com/wootube/ioi/service/support/Config.java
> +public class Config {
OOOConfig 로 이름을 변경해도 좋지 않을까요?

2019-08-15 12:26 UTC, MrKwon commented on src/main/java/com/wootube/ioi/web/controller/VideoController.java
> +		videoRequestDto = videoService.create(uploadFile, videoRequestDto);
Argument 로 들어온 ``videoRequestDto`` 를 조작하는 것이 괜찮을까요?

2019-08-15 12:26 UTC, MrKwon commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +		Video video = modelMapper.map(videoRequestDto, Video.class);
ModelMapper 를 사용한 특별한 이유가 있을까요?

2019-08-15 12:26 UTC, MrKwon commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +		video.setContentPath(videoUrl);
ModelMapper 를 꼭 사용하더라도 setter 를 없앨 수 있을 것 같아요.

2019-08-15 12:26 UTC, MrKwon commented on src/main/java/com/wootube/ioi/domain/model/Video.java
> +	@Column(updatable = false)
새로운 거 알아갑니다 👍

2019-08-16 07:27 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/support/Config.java
> +public class Config {
ModelConfig로 이름을 변경했습니다. 혹시 더 좋은 이름이 있을까요?

2019-08-16 07:42 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +		Video video = modelMapper.map(videoRequestDto, Video.class);
dto를 entity로 또는 entity를 dto로 바꾸는 과정에서 **setter** 또는 **생성자** 를 이용할 수 있는데요. 
생성자를 사용하지 않았던 이유는 인자가 많아졌을 때 해당 코드를 읽기에 불편함이 있을거같아 사용하지 않았습니다.
또, 직접 setter를 이용하면 필드의 개수만큼 코드를 작성해야하기 때문에 ModelMapper를 이용해 한 줄로 코드를 작성하고 싶었습니다.
답변을 작성하며 생각해보니 builder패턴을 통해 생성자를 사용하려했을 때의 단점을 극복할 수 있을거같은데 어떻게 생각하시나요?

2019-08-16 07:50 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +		video.setContentPath(videoUrl);
contentPath를 Video객체에 set하는 과정은
`video.setContentPath(videoUrl);` -> `videoRequestDto.setContentPath(videoUrl);`으로 수정하며 set메소드를 사용하지 않을 수 있었습니다.

`video.setOriginFileName(originFileName);` 이 부분에 대해서는 감이 잘 안오네요. 혹시 의견을 주실 수 있나요?

2019-08-16 08:01 UTC, yjll1019 commented
안녕하세요! 리뷰이 티버입니다~
제가 피드백을 늦게 확인해서 반영이 늦어졌네요. 죄송합니다.
코멘트 달아주신 부분에 대해서 답변 남겼습니다. 
제가 수정한 부분 중에서 더 좋은 의견이 있으시면 말씀해주세요~ 
감사합니다.

2019-08-16 09:47 UTC, MrKwon commented on src/main/java/com/wootube/ioi/service/support/Config.java
> +public class Config {
좋은 것 같아요 !

2019-08-17 02:36 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/web/controller/VideoController.java
> +		videoRequestDto = videoService.create(uploadFile, videoRequestDto);
VideoResponseDto 를 만들어 수정했습니다~~!

2019-08-17 03:24 UTC, merged