[효오, 비모] 댓글 CRUD
woowahan-ioi/miniprojects-2019 pull request #27
Opened 2019-08-14 09:14 UTC by hyojaekim

테스트는 계속해서 추가하고 있습니다 ㅠ

2019-08-15 05:24 UTC, yjll1019 approved these changes
중간 중간 주석 처리로 아직 구현되지 않은 부분을 적어주셔서 쉽게 이해할 수 있었습니다 👍

2019-08-16 13:02 UTC, backlo requested changes
구현 잘해 주셨네요! 💯 
몇개 없지만 피드백 드립니다~~

2019-08-16 13:02 UTC, backlo commented on src/main/java/com/wootube/ioi/domain/model/Comment.java
> +
주석처리 부분 빼주세요~ 😄

2019-08-16 13:02 UTC, backlo commented on src/main/java/com/wootube/ioi/domain/model/Comment.java
> +@EqualsAndHashCode(of = "id")
of 사용 굳! 👍

2019-08-16 13:02 UTC, backlo commented on src/main/java/com/wootube/ioi/service/CommentService.java
> +
여기도 주석 빼주세요~~

2019-08-16 13:02 UTC, backlo commented on src/main/java/com/wootube/ioi/service/CommentService.java
> +                comment.getUpdateTime());
Builder 패턴 쓰시는게 어떨까요??

2019-08-16 13:02 UTC, backlo commented on src/main/java/com/wootube/ioi/service/dto/CommentRequestDto.java
> +@AllArgsConstructor
lombok 사용시 NoArgs빼고 사용을 지양하라고 되어있습니다. AllArgs말고 빌더패턴을 사용해 보는게 어떨까요????
참고자료 입니다 😄 
https://kwonnam.pe.kr/wiki/java/lombok/pitfall

2019-08-17 05:08 UTC, merged

2019-08-17 07:44 UTC, SEOKHYOENCHOI commented on src/main/java/com/wootube/ioi/domain/model/Comment.java
> +
Video와 합칠 때 적용하기 위해서 주석처리 했어요!
합치면서 주석 제거할게요

2019-08-17 07:54 UTC, SEOKHYOENCHOI commented on src/main/java/com/wootube/ioi/service/dto/CommentRequestDto.java
> +@AllArgsConstructor
Model <-> Dto 변환을 위해서 사용한 Annotation인데, 글을 읽어보니 문제가 생길 수도 있을 것 같네요 👍 
빌더패턴이나 Assembler를 사용하면 각 Dto, Model 마다 계속 변환 메서드를 작성해야돼서 불편함이 있을 것 같아요.
ModelMapper를 적용해볼게요.